# Generated by Django 3.1.7 on 2021-04-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('details', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Lowest', 'Lowest'), ('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Highest', 'Highest')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
