# Generated by Django 3.2.3 on 2021-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_task_date_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.DateTimeField(null=True),
        ),
    ]
