# Generated by Django 3.2.3 on 2021-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_auto_20210608_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
