# Generated by Django 3.2.3 on 2021-06-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='Click', max_length=255, null=True),
        ),
    ]
