# Generated by Django 3.2.3 on 2021-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0015_auto_20210609_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='Select Category', max_length=50, null=True),
        ),
    ]
