# Generated by Django 3.2.3 on 2021-06-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0017_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
    ]
