# Generated by Django 3.2.3 on 2021-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0022_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Lowest'), ('2', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Highest', 'Highest')], max_length=255, null=True),
        ),
    ]
