# Generated by Django 3.2.3 on 2021-07-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0023_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Lowest', '1'), ('Low', '2'), ('Normal', 'Normal'), ('High', 'High'), ('Highest', 'Highest')], max_length=255, null=True),
        ),
    ]
