# Generated by Django 3.2.3 on 2021-07-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0025_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Lowest'), ('2', 'Low'), ('3', 'Normal'), ('4', 'High'), ('5', 'Highest')], max_length=255, null=True),
        ),
    ]
