# Generated by Django 3.2.3 on 2021-07-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0026_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Lowest', 'Lowest'), ('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Highest', 'Highest')], max_length=255, null=True),
        ),
    ]
